### ISSUE TITLE
Ability to modify content in a stream

### ISSUE THREAD

**Issue by cgilling** [richardlehane/mscfb#7]
I'm in the middle of trying to transition some code that I have written in C/C++ over to go and one of the pieces that I have is something that will go into the file and turn off macros in `.doc` files so as to make them safer to process in ms word. In order to do this, I merely go into the doc file and flip the length of the micro section to be 0 so that word no longer picks up the macros.

To enable this in go I would need the ability to be able to modify streams. I'm wondering if you would be open to the idea of having `File` object allow overwriting (not appending as that sounds much more complicated).

**Comment by richardlehane** [comment]
Hi cgilling
I've just had a quick go at adding the io.Seeker and io.Writer interfaces to File objects. 
This should allow you to seek within a File and change bytes.
Make sure your underlying source is an io.WriterAt and has write permissions if a file.

Current implementation is quick and nasty and the test function (https://github.com/richardlehane/mscfb/blob/master/mscfb_test.go#L146) isn't at all comprehensive. So please consider this experimental feature for now.

Will be interested to hear how you get on with it.

cheers
Richard

**Comment by richardlehane** [comment]
some tests now failing, this needs a bit more work, shouldn't take long

**Comment by richardlehane** [comment]
basic tests, now passing. Added ReadAt() and WriteAt() methods too. See doco at https://godoc.org/github.com/richardlehane/mscfb for usage. Think this is ready to go now.

**Comment by cgilling** [comment]
sweet thanks, I'll give it a spin soon

**Comment by cgilling** [comment]
Just a quick update, works great, I was able to implement what I wanted and set 100,000 random documents through it (of various filetypes include non mscfb filetypes) and no crashing.

Thanks again for the quick turnaround on the request

**Comment by richardlehane** [comment]
Glad to hear, thx for the request
